language: minimal

env:
  global:
    - IMAGE_TAG=$TRAVIS_COMMIT

stages:
  - test
  - build
  - build_xpub_postgres

jobs:
  include:
    - stage: test
      language: node_js
      name: Test
      node_js:
        - 12.15.0
      script:
        - make lint
        - make test

    - stage: build
      name: Build
      script: make build
      deploy:
        provider: script
        script: make push
        on:
          branch: master

    - stage: build
      name: Build Xpub Postgres
      script: make build_xpub_postgres
      deploy:
        provider: script
        script: make push_xpub_postgres
        on:
          branch: master
