ARG image_tag=latest

FROM liberoadmin/reviewer_server_typescript:${image_tag}

MAINTAINER eLife Reviewer Product Team <reviewer-product@elifesciences.org>

WORKDIR /app

EXPOSE 3000

HEALTHCHECK --interval=1m --timeout=1s \
	CMD curl -f http://localhost:3000/health || exit 1

CMD ["node", "dist/main.js"]
