ARG image_tag=latest

FROM liberoadmin/reviewer_server_typescript:${image_tag} as server_typescript

FROM node:10-alpine
MAINTAINER eLife Reviewer Product Team <reviewer-product@elifesciences.org>

WORKDIR /app

COPY --from=server_typescript /app/node_modules/ ./node_modules/
COPY --from=server_typescript /app/dist/ ./dist/

EXPOSE 3000

HEALTHCHECK --interval=1m --timeout=1s \
	CMD curl -f http://localhost:3000/health || exit 1

CMD ["node", "dist/main.js"]
