ARG image_tag=latest

FROM node:10-alpine
MAINTAINER eLife Reviewer Product Team <reviewer-product@elifesciences.org>

WORKDIR /app

COPY  tsconfig.build.json \
      tsconfig.json \
      tslint.json \
      package.json \
      ./

COPY src/ ./src/
RUN yarn &&\
    yarn build
